### PR TITLE
Refactor mappings

### PR DESCRIPTION
**Pull request by nfnty**
Is backwards compatible with old mappings.

### CODE REVIEW

**Comment by romainl** [comment]
Thank you. I just created the `nfnty-mappings` branch from this pull request. This looks interesting but I need to finish the current refactoring before giving your PR the attention it deserves.

**Comment by nfnty** [comment]
This was just rebased and updated.

**Comment by nfnty** [comment]
Rebased again. Could this be merged soon?

**Comment by nfnty** [comment]
ping @romainl

**Comment by romainl** [comment]
Sorry @nfnty, I'll get to it tonight or tomorrow night.

**Pull request merged**
