### PR TITLE
Toggle the long/short path in current location/quikfix window

### PR DESCRIPTION
**Pull request by lsaint**
2e385e6

Toggle the long/short path in current location/quikfix window.
Only available when location/quickfix is open.

Example:
    `nmap <F7> <Plug>(qf_shorten_path_toggle)`

### CODE REVIEW

**Comment by romainl** [comment]
@lsaint thank you. Give me a day or two to come back with a review.

**Comment by romainl** [comment]
More like three weeks…

Thank you, I tried my hands at what I considered a simpler approach in the mean time but it kept becoming more complex for no real benefit over this.

Thank you.

**Comment by jonwalstedt** [comment]
@romainl This would be a really nice feature to have, any reason to why this merge request reverted? Is there an alternative approach or something similar in the pipeline?

**Comment by romainl** [comment]
@jonwalstedt I agree it would be nice but this specific implementation is flawed: it threw errors on startup when doing `$ vim -q foobar`, for example.

FWIW, the approach doesn't seem inherently wrong but it is not complete.

**Pull request merged**
